CREATE TABLE "biz_equivalents" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "biz_equivalents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"care_skill" text,
	"biz_equivalent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"skill_id" bigint
);
--> statement-breakpoint
CREATE TABLE "care_activity_candidates" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" varchar(36) NOT NULL,
	"raw_title" text NOT NULL,
	"raw_start" timestamp with time zone NOT NULL,
	"raw_end" timestamp with time zone NOT NULL,
	"score" numeric,
	"extracted_json" jsonb,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "skills" ALTER COLUMN "count" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "care_activities" ADD COLUMN "title" text;--> statement-breakpoint
ALTER TABLE "care_activities" ADD COLUMN "star_statement" text;--> statement-breakpoint
ALTER TABLE "care_activities" ADD COLUMN "summary" text;--> statement-breakpoint
ALTER TABLE "skills" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "skills" ADD COLUMN "icon" text;--> statement-breakpoint
ALTER TABLE "skills" ADD COLUMN "user_id" bigint;--> statement-breakpoint
ALTER TABLE "skills" ADD COLUMN "tendency" text DEFAULT 'まれに見られる';--> statement-breakpoint
ALTER TABLE "biz_equivalents" ADD CONSTRAINT "biz_equivalents_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "public"."skills"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "skills" ADD CONSTRAINT "skills_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_skills" DROP COLUMN "tendency";--> statement-breakpoint
ALTER TABLE "activity_skills" DROP COLUMN "source";--> statement-breakpoint
ALTER TABLE "skills" DROP COLUMN "category";--> statement-breakpoint
DROP POLICY "AIケアワークポートフォリオ" ON "users" CASCADE;--> statement-breakpoint
CREATE POLICY "テスト用" ON "users" AS PERMISSIVE FOR SELECT TO "anon" USING (true);